language: node_js
node_js:
  - "v12.14.1"

cache:
  yarn: true

stages:
  - Test
  - name: Release
    if: tag IS present

jobs:
  include:
    - stage: Test
      name: Unit Tests
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.21.1
        - export PATH="$HOME/.yarn/bin:$PATH"
      install:
        - yarn --frozen-lockfile
      script:
        - yarn test
      after_script:
        # Push tests coverage data to Codecov:
        - npx codecov

    - stage: Release
      name: Github Release
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.21.1
        - export PATH="$HOME/.yarn/bin:$PATH"
      install:
        - yarn --frozen-lockfile
      script: skip
      before_deploy:
        - yarn ci:generate:release_notes
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        edge:
          branch: master
        release_notes_file: ./RELEASE_NOTES.md

# Limit branches builds to "master" & "develop" ones:
branches:
  only:
    - develop
    - master
    - /^v\d+\.\d+\.\d+(-(alpha|beta)\.\d+)?$/

notifications:
  email:
    on_failure: change
    on_success: never
