language: node_js
node_js:
  - "v12.16.3"

cache:
  yarn: true
  directories:
    - nodes_modules
    - website/nodes_modules

stages:
  - Test
  - name: Release
    if: repo = "SocialGouv/monitorer"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn --frozen-lockfile

jobs:
  include:
    - stage: Test
      name: Unit Tests
      after_script:
        - npx codecov

    - stage: Test
      name: Website
      before_install:
        - cd website

    - stage: Release
      name: Github Release
      if: tag IS present
      script: skip
      before_deploy:
        - yarn ci:generate:release_notes
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        edge:
          branch: master
        release_notes_file: ./RELEASE_NOTES.md
        on:
          tags: true

    - stage: Release
      name: Github Pages
      if: branch = "master" AND type != "pull_request"
      before_install:
        - cd website
      script:
        - git config --global user.name "${GITHUB_NAME}"
        - git config --global user.email "${GITHUB_EMAIL}"
        - echo "machine github.com login ${GITHUB_NAME} password ${GITHUB_TOKEN}" > ~/.netrc
        - GIT_USER="${GITHUB_NAME}" yarn publish-gh-pages

# Limit branches builds to "master" & "develop" ones:
branches:
  only:
    - develop
    - master
    - /^v\d+\.\d+\.\d+(-(alpha|beta)\.\d+)?$/

notifications:
  email:
    on_failure: change
    on_success: never
