version: "3"

services:
  # https://github.com/docker-library/mongo/issues/329#issuecomment-460858099
  db:
    image: mongo:4-bionic
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    environment:
      MONGO_INITDB_NON_ROOT_DATABASE: ${MONGO_NAME}
      MONGO_INITDB_NON_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_NON_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db
      - ./scripts/docker/initialize_db.sh:/docker-entrypoint-initdb.d/initialize.sh

  docusaurus:
    build:
      context: .
      dockerfile: image.website.Dockerfile
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./docs:/app/docs
      - ./website/blog:/app/website/blog
      - ./website/core:/app/website/core
      - ./website/i18n:/app/website/i18n
      - ./website/pages:/app/website/pages
      - ./website/static:/app/website/static
      - ./website/sidebars.json:/app/website/sidebars.json
      - ./website/siteConfig.js:/app/website/siteConfig.js
    working_dir: /app/website

volumes:
  mongo-data:
