module.exports = {
  bail: true,
  collectCoverage: true,
  collectCoverageFrom: ["**/*.js"],
  coveragePathIgnorePatterns: [
    "<rootDir>/build",
    "<rootDir>/coverage",
    "<rootDir>/dist",
    "<rootDir>/jest.config.js",
    "<rootDir>/node_modules",
    "<rootDir>/scripts",
    "<rootDir>/src/web/public/js/vendors",
    "<rootDir>/tests",
    "<rootDir>/website",
  ],
  setupFilesAfterEnv: ["<rootDir>/tests/jest.setup.js"],
  testPathIgnorePatterns: [
    "<rootDir>/build",
    "<rootDir>/coverage",
    "<rootDir>/dist",
    "<rootDir>/jest.config.js",
    "<rootDir>/node_modules",
    "<rootDir>/scripts",
    "<rootDir>/src/web/public/js/vendors",
    "<rootDir>/tests",
    "<rootDir>/website",
  ],
};
